[grafana]
url = "https://grafana.mydomain.com"
token = "xxxx"
influx_ql_uid = "xxxx"

[influxdb]
url = "http://localhost"
org = "ORG-NAME"
bucket = "bucket-name"
port = 8086
token = "xxxx"

[instruments]
[instruments.hatpro]
one-site = "template_hatpro_one-station.json"

[instruments.chm15k]
one-site = "template_chm15k_one-station.json"

[instruments.rpg-fmcw-94]
one-site = "template_rpg-fmcw-94_one-station.json"

[instruments.rpg-fmcw-35]
one-site = "template_rpg-fmcw-35_one-station.json"
